#!/bin/bash

# Do we even have instance store?

howmanydisks=$(curl http://169.254.169.254/latest/meta-data/block-device-mapping/ | grep -c ephemeral)

if [ $howmanydisks -eq 0 ]

then

echo "No instance store available."

exit 2

fi

declare -a ephemeral_disks

# Enumerate the local disks and create PVs

for i in $(curl http://169.254.169.254/latest/meta-data/block-device-mapping/ | grep ephemeral)

do

diskname=$(curl http://169.254.169.254/latest/meta-data/block-device-mapping/$i | sed 's/^s/xv/')

pvcreate /dev/$diskname

if [ $? -eq 0 ] 

then

ephemeral_disks=("${ephemeral_disks[@]}" "/dev/$diskname")

fi

done


vgcreate -n instance_store ${ephemeral_disks[@]}

lvcreate -n optlv -l 100%FREE instance_store

mkfs.ext4 -m0 /dev/mapper/instance_store-optlv

